# Generated by Django 5.2.4 on 2025-07-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'Dollar'), ('rub', 'Rouble')], default='usd', max_length=10),
        ),
    ]
