# Generated by Django 5.2.4 on 2025-07-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax_id',
        ),
    ]
