# Generated by Django 5.2.4 on 2025-07-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_discount_order_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='tax',
            old_name='tax_amount',
            new_name='amount',
        ),
    ]
